const ACTIONS = {
    FETCHING: 'FETCHING',
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE'
}

const FLIGHTS = {
    BUSINESS_FLIGHTS: 'BUSINESS_FLIGHTS',
    CHEAP_FLIGHTS: 'CHEAP_FLIGHTS'
}

export { ACTIONS, FLIGHTS }