const ACTIONS = {
    FETCHING: '_FETCHING',
    SUCCESS: '_SUCCESS',
    FAILURE: '_FAILURE'
}

const FLIGHTS = {
    BUSINESS_FLIGHTS: 'BUSINESS_FLIGHTS',
    CHEAP_FLIGHTS: 'CHEAP_FLIGHTS'
}

const FLIGHT_TYPES = {
    BUSINESS: 'business',
    CHEAP: 'cheap'
}

export { ACTIONS, FLIGHTS, FLIGHT_TYPES }